services:
  backend:
    build: ./backend
    container_name: psql_db
    image: postgres:16
    restart: always
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auto_incident_network

volumes:
  postgres_data:

networks:
  auto_incident_network:
